# Generated by Django 2.2.2 on 2019-06-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.CharField(max_length=200)),
                ('unixtime', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=200)),
                ('s3_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('orig_url', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
