# Generated by Django 2.2.2 on 2019-06-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='uuid',
        ),
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
