# Generated by Django 2.2.2 on 2019-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0003_auto_20190626_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='button_id',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='image',
        ),
        migrations.AddField(
            model_name='meme',
            name='s3_url',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
