# Generated by Django 2.2.2 on 2019-06-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gitLink',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
