branch-defaults:
  master:
    environment: django-turorial-dev
environment-defaults:
  django-env:
    branch: null
    repository: null
  django-turorial-dev:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
